export const CLIENTS = {
  vinoy: {
    id:'vinoy', name:'The Vinoy Renaissance', location:'St. Petersburg, FL',
    contact:'Maria Rodriguez', email:'maria@vinoy.com', retainer:6000,
    package:'Cinematic Partner', health:'On Track',
    nextShoot:'Mar 14', shootTime:'8:00 AM - 4:00 PM',
    shootLocation:'Pool Deck & Lobby', daysUntil:4,
    directBookings:68, directLast:54, commissionSaved:12600,
    contentDelivered:14, contentPlanned:16,
    avgViews:11200, websiteTraffic:4820, websiteTrafficLast:3940,
    directTrend:[32,38,44,51,58,62,68],
    otaTrend:[68,62,56,49,42,38,32],
    trafficTrend:[2800,3100,3400,3700,4100,4500,4820],
    invoiceStatus:'paid', since:'January 2026',
    avatar:'M', color:'#1B3A4B', accentColor:'#C9A84C', font:'Playfair Display',
    shootDeliverables:['2x Instagram Reels','1x Property Tour','Staff Spotlight - GM'],
    stripeCustomerId:'cus_vinoy_stub',
  },
  surfcomber: {
    id:'surfcomber', name:'Kimpton Surfcomber', location:'Miami Beach, FL',
    contact:'David Kim', email:'david@surfcomber.com', retainer:5000,
    package:'Content Partner', health:'On Track',
    nextShoot:'Mar 20', shootTime:'9:00 AM - 3:00 PM',
    shootLocation:'Beach & Rooftop Pool', daysUntil:10,
    directBookings:55, directLast:44, commissionSaved:9800,
    contentDelivered:11, contentPlanned:14,
    avgViews:8900, websiteTraffic:3650, websiteTrafficLast:2900,
    directTrend:[28,33,38,44,49,52,55],
    otaTrend:[72,67,62,56,51,48,45],
    trafficTrend:[2100,2300,2600,2900,3100,3400,3650],
    invoiceStatus:'pending', since:'February 2026',
    avatar:'D', color:'#0077B6', accentColor:'#48CAE4', font:'Montserrat',
    shootDeliverables:['3x Instagram Reels','Beach Property Tour'],
    stripeCustomerId:'cus_surfcomber_stub',
  },
  biltmore: {
    id:'biltmore', name:'Biltmore Hotel', location:'Coral Gables, FL',
    contact:'Sandra Okafor', email:'sandra@biltmore.com', retainer:4000,
    package:'Starter Package', health:'Attention',
    nextShoot:'Mar 28', shootTime:'10:00 AM - 2:00 PM',
    shootLocation:'Restaurant & Spa', daysUntil:18,
    directBookings:41, directLast:36, commissionSaved:6200,
    contentDelivered:8, contentPlanned:12,
    avgViews:6100, websiteTraffic:2400, websiteTrafficLast:2100,
    directTrend:[22,26,30,34,36,39,41],
    otaTrend:[78,74,70,66,64,61,59],
    trafficTrend:[1600,1800,1900,2000,2100,2250,2400],
    invoiceStatus:'overdue', since:'February 2026',
    avatar:'S', color:'#2C1810', accentColor:'#8B6914', font:'Cormorant Garamond',
    shootDeliverables:['Restaurant Feature','Spa & Pool Tour'],
    stripeCustomerId:'cus_biltmore_stub',
  },
};

export const INVOICES = [
  { id:1, number:'INV-2026-031', clientId:'vinoy',      client:'Maria Rodriguez', property:'The Vinoy Renaissance', issueDate:'Mar 1, 2026',  dueDate:'Mar 15, 2026', status:'pending',    amount:6000, lineItems:[{description:'Monthly Retainer - Cinematic Partner',note:'March 2026',qty:1,rate:6000,amount:6000}] },
  { id:2, number:'INV-2026-030', clientId:'surfcomber', client:'David Kim',        property:'Kimpton Surfcomber',    issueDate:'Mar 1, 2026',  dueDate:'Mar 15, 2026', status:'pending', amount:5000, lineItems:[{description:'Monthly Retainer - Content Partner',note:'March 2026',qty:1,rate:4500,amount:4500},{description:'Event Coverage Add-on',note:'Feb 28',qty:1,rate:500,amount:500}] },
  { id:3, number:'INV-2026-029', clientId:'biltmore',   client:'Sandra Okafor',   property:'Biltmore Hotel',        issueDate:'Feb 28, 2026', dueDate:'Mar 10, 2026', status:'overdue', amount:4000, lineItems:[{description:'Monthly Retainer - Starter Package',note:'March 2026',qty:1,rate:4000,amount:4000}] },
  { id:4, number:'INV-2026-028', clientId:'vinoy',      client:'Maria Rodriguez', property:'The Vinoy Renaissance', issueDate:'Feb 1, 2026',  dueDate:'Feb 15, 2026', status:'paid',    amount:6000, lineItems:[{description:'Monthly Retainer - Cinematic Partner',note:'February 2026',qty:1,rate:6000,amount:6000}] },
  { id:5, number:'INV-2026-027', clientId:'surfcomber', client:'David Kim',        property:'Kimpton Surfcomber',    issueDate:'Feb 1, 2026',  dueDate:'Feb 15, 2026', status:'paid',    amount:4500, lineItems:[{description:'Monthly Retainer - Content Partner',note:'February 2026',qty:1,rate:4500,amount:4500}] },
  { id:6, number:'INV-2026-026', clientId:'biltmore',   client:'Sandra Okafor',   property:'Biltmore Hotel',        issueDate:'Feb 1, 2026',  dueDate:'Feb 15, 2026', status:'paid',    amount:4000, lineItems:[{description:'Monthly Retainer - Starter Package',note:'February 2026',qty:1,rate:4000,amount:4000}] },
];

export const GANTT = {
  vinoy: [
    {id:1,name:'Pre-Production Planning',phase:'preproduction',start:0, duration:5,status:'completed',startDate:'Mar 1', endDate:'Mar 5', assignee:'Jordan',   deliverables:['Shot list','Location scouting','Call sheet'],daysLeft:0},
    {id:2,name:'Brand Identity Review',  phase:'review',       start:3, duration:4,status:'completed',startDate:'Mar 4', endDate:'Mar 7', assignee:'Maria R.', deliverables:['Brand approval','Brief sign-off'],daysLeft:0},
    {id:3,name:'Shoot Day - Pool Deck',  phase:'production',   start:7, duration:2,status:'completed',startDate:'Mar 8', endDate:'Mar 9', assignee:'Jordan',   deliverables:['2x Reels','B-roll package'],daysLeft:0},
    {id:4,name:'Shoot Day - Lobby',      phase:'production',   start:10,duration:2,status:'completed',startDate:'Mar 11',endDate:'Mar 12',assignee:'Jordan',   deliverables:['Suite walkthrough','Staff spotlight'],daysLeft:0},
    {id:5,name:'Post-Production Edit',   phase:'postproduction',start:12,duration:6,status:'active',  startDate:'Mar 13',endDate:'Mar 18',assignee:'Jordan',   deliverables:['Color grade','Sound mix','Captions','Export'],daysLeft:3},
    {id:6,name:'Client Review',          phase:'review',       start:18,duration:5,status:'upcoming', startDate:'Mar 19',endDate:'Mar 23',assignee:'Maria R.', deliverables:['Feedback round 1','Revision requests'],daysLeft:8},
    {id:7,name:'Revisions & Export',     phase:'postproduction',start:23,duration:4,status:'upcoming',startDate:'Mar 24',endDate:'Mar 27',assignee:'Jordan',   deliverables:['Final cut','All formats'],daysLeft:12},
    {id:8,name:'Content Delivery',       phase:'delivery',     start:27,duration:3,status:'upcoming', startDate:'Mar 28',endDate:'Mar 30',assignee:'Jordan',   deliverables:['Drive delivery','Captions','Post schedule'],daysLeft:15},
  ],
  surfcomber: [
    {id:1,name:'Pre-Production', phase:'preproduction', start:0, duration:4,status:'completed',startDate:'Mar 1', endDate:'Mar 4', assignee:'Jordan',deliverables:['Shot list','Call sheet'],daysLeft:0},
    {id:2,name:'Shoot Day',      phase:'production',    start:5, duration:3,status:'completed',startDate:'Mar 6', endDate:'Mar 8', assignee:'Jordan',deliverables:['3x Reels','B-roll'],daysLeft:0},
    {id:3,name:'Post-Production',phase:'postproduction',start:9, duration:8,status:'active',   startDate:'Mar 10',endDate:'Mar 17',assignee:'Jordan',deliverables:['Edit','Color','Export'],daysLeft:2},
    {id:4,name:'Client Review',  phase:'review',        start:17,duration:5,status:'upcoming', startDate:'Mar 18',endDate:'Mar 22',assignee:'Team',  deliverables:['Feedback','Revisions'],daysLeft:6},
    {id:5,name:'Final Delivery', phase:'delivery',      start:22,duration:4,status:'upcoming', startDate:'Mar 23',endDate:'Mar 26',assignee:'Jordan',deliverables:['All files','Captions'],daysLeft:10},
  ],
  biltmore: [
    {id:1,name:'Brief & Planning',  phase:'preproduction', start:2, duration:5,status:'completed',startDate:'Mar 3', endDate:'Mar 7', assignee:'Jordan',deliverables:['Creative brief','Location plan'],daysLeft:0},
    {id:2,name:'Shoot Day',         phase:'production',    start:8, duration:2,status:'completed',startDate:'Mar 9', endDate:'Mar 10',assignee:'Jordan',deliverables:['Restaurant','Spa tour'],daysLeft:0},
    {id:3,name:'Post-Production',   phase:'postproduction',start:11,duration:9,status:'active',   startDate:'Mar 12',endDate:'Mar 20',assignee:'Jordan',deliverables:['Full edit package'],daysLeft:5},
    {id:4,name:'Review & Revisions',phase:'review',        start:20,duration:6,status:'upcoming', startDate:'Mar 21',endDate:'Mar 26',assignee:'GM',   deliverables:['Feedback','Changes'],daysLeft:10},
    {id:5,name:'Delivery',          phase:'delivery',      start:26,duration:4,status:'upcoming', startDate:'Mar 27',endDate:'Mar 30',assignee:'Jordan',deliverables:['Final assets'],daysLeft:14},
  ],
};

export const CONTENT = [
  {id:1, clientId:'vinoy',      title:'Poolside Morning Vibes',        tag:'Reel',      views:'12.4K',hot:true, date:'Mar 8'},
  {id:2, clientId:'vinoy',      title:'Suite Walkthrough - Ocean View',tag:'Tour',      views:'8.1K', hot:true, date:'Mar 5'},
  {id:3, clientId:'vinoy',      title:'Chef Carlos - Kitchen Stories', tag:'Spotlight', views:'5.7K', hot:false,date:'Feb 28'},
  {id:4, clientId:'vinoy',      title:'Guest Check-In Experience',     tag:'Reel',      views:'19.2K',hot:true, date:'Feb 22'},
  {id:5, clientId:'vinoy',      title:'Rooftop Sunset Sessions',       tag:'Reel',      views:'9.4K', hot:false,date:'Feb 15'},
  {id:6, clientId:'vinoy',      title:'The Vinoy - Brand Story',       tag:'Brand',     views:'6.8K', hot:false,date:'Feb 8'},
  {id:7, clientId:'vinoy',      title:'Spa & Wellness Tour',           tag:'Tour',      views:'4.2K', hot:false,date:'Feb 1'},
  {id:8, clientId:'vinoy',      title:'New Year Gala Recap',           tag:'Event',     views:'22.1K',hot:true, date:'Jan 3'},
  {id:9, clientId:'surfcomber', title:'Beach at Golden Hour',          tag:'Reel',      views:'14.2K',hot:true, date:'Mar 7'},
  {id:10,clientId:'surfcomber', title:'Rooftop Pool Experience',       tag:'Tour',      views:'7.8K', hot:false,date:'Mar 3'},
  {id:11,clientId:'surfcomber', title:'Miami Sunrise Check-In',        tag:'Reel',      views:'11.1K',hot:true, date:'Feb 24'},
  {id:12,clientId:'biltmore',   title:'Historic Lobby Reveal',        tag:'Brand',     views:'9.1K', hot:true, date:'Mar 2'},
  {id:13,clientId:'biltmore',   title:'Fine Dining Experience',       tag:'Spotlight', views:'5.3K', hot:false,date:'Feb 25'},
];

export const PMS_SYSTEMS = [
  {id:'opera',     name:'Opera Cloud',    vendor:'Oracle',        icon:'🏨',tier:'Enterprise',    status:'available',authType:'OAuth 2.0',webhooks:true, dataPoints:['Bookings','Revenue','Channel Split','Occupancy','ADR','RevPAR']},
  {id:'cloudbeds', name:'Cloudbeds',       vendor:'Cloudbeds',     icon:'☁️',tier:'Mid-Market',    status:'connected',authType:'OAuth 2.0',webhooks:true, dataPoints:['Bookings','Channel Split','OTA vs Direct','Revenue']},
  {id:'mews',      name:'Mews',            vendor:'Mews Systems',  icon:'⚡',tier:'Modern Boutique',status:'available',authType:'API Key',  webhooks:true, dataPoints:['Reservations','Revenue','Source Breakdown']},
  {id:'apaleo',    name:'Apaleo',          vendor:'Apaleo',        icon:'🔌',tier:'API-First',     status:'available',authType:'OAuth 2.0',webhooks:true, dataPoints:['All booking data','Channel attribution']},
  {id:'lightspeed',name:'Lightspeed PMS',  vendor:'Shiji',         icon:'💡',tier:'Lifestyle',     status:'available',authType:'API Key',  webhooks:true, dataPoints:['Bookings','Revenue','Guest Profiles']},
  {id:'clock',     name:'Clock PMS+',      vendor:'Clock Software',icon:'🕐',tier:'Independent',   status:'available',authType:'REST API', webhooks:false,dataPoints:['Bookings','Channel Split','Revenue']},
  {id:'custom',    name:'Custom Webhook',  vendor:'Any PMS',       icon:'🛠',tier:'Universal',     status:'available',authType:'HMAC Secret',webhooks:true,dataPoints:['Any JSON payload']},
];
